# Generated by Django 3.1.4 on 2021-01-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maddi_app', '0002_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='receiver_name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='receiver_phone_number',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
