# Generated by Django 3.1.4 on 2021-01-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maddi_app', '0008_payment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='delivery_receipt_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_price',
            field=models.CharField(max_length=40),
        ),
    ]
