# Generated by Django 3.1.4 on 2021-01-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maddi_app', '0009_auto_20210116_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='delivery_receipt_number',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='shipping_price',
            field=models.BigIntegerField(),
        ),
    ]
